require_relative 'app'
require_relative "app/utils/activerecord/rake"
load "./app/utils/daemon.rake"

namespace :proto do
  desc 'Build protobuf definitions'
  task :build do
    sh "protoc --proto_path=proto --ruby_out=app/messages proto/*.proto"
    sh "protoc --proto_path=proto --ruby_out=app/messages proto/**/*.proto"
    sh "protoc --proto_path=proto --ruby_out=app/messages proto/**/**/*.proto"
  end
end

desc "Start IRB."
task :irb do
  sh 'irb -r ./app.rb'
end

desc "Run tests."
task :test do
  exec "cutest -r ./tests/helper.rb ./tests/*_test.rb"
end

task :default => :test
