# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/bridge_info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.BridgeInfo" do
  end
end

module Proto
  BridgeInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.BridgeInfo").msgclass
end
