# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/controller_info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.ControllerInfo" do
  end
end

module Proto
  ControllerInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ControllerInfo").msgclass
end
