# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/data_session.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'models/daemon_info_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.DataSession" do
    optional :initiator, :message, 1, "proto.DaemonInfo"
    optional :responder, :message, 2, "proto.DaemonInfo"
    optional :created_at, :message, 3, "google.protobuf.Timestamp"
    optional :type, :enum, 4, "proto.DataSession.Type"
    optional :uuid, :string, 5
  end
  add_enum "proto.DataSession.Type" do
    value :UNSET, 0
    value :PHALA_TEE, 1
    value :PHALA_BRIDGE, 2
  end
end

module Proto
  DataSession = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.DataSession").msgclass
  DataSession::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.DataSession.Type").enummodule
end
