# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/worker_info.proto

require 'google/protobuf'

require 'models/utils/account_pb'
require 'models/worker_states_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.WorkerInfo" do
    optional :account, :message, 1, "proto.Account"
    optional :description, :string, 2
    optional :states, :message, 3, "proto.WorkerStates"
    optional :status, :enum, 4, "proto.WorkerInfo.Status"
  end
  add_enum "proto.WorkerInfo.Status" do
    value :UNKNOWN, 0
    value :IDLE, 1
    value :SYNCING, 2
    value :WAITING, 3
    value :INTENTION_SET, 4
    value :ERROR, 5
  end
end

module Proto
  WorkerInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.WorkerInfo").msgclass
  WorkerInfo::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.WorkerInfo.Status").enummodule
end
