# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/worker_states.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.WorkerStates" do
  end
end

module Proto
  WorkerStates = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.WorkerStates").msgclass
end
