# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/utils/empty.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.utils.Empty" do
  end
end

module Proto
  module Utils
    Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.utils.Empty").msgclass
  end
end
