# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'models/utils/empty_pb'
require 'models/utils/message_target_pb'
require 'models/worker_info_pb'
require 'messages/error_pb'
require 'messages/keepalive_pb'
require 'messages/request_provisioning_pb'
require 'messages/should_provision_pb'
require 'messages/data_frame_pb'
require 'messages/worker_should_run_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.TunnelMessage" do
    optional :source, :enum, 1, "proto.utils.MessageTarget"
    optional :target, :enum, 2, "proto.utils.MessageTarget"
    optional :created_at, :message, 3, "google.protobuf.Timestamp"
    optional :ref, :string, 4
    repeated :related_refs, :string, 5
    oneof :payload do
      optional :error, :message, 6, "proto.Error"
      optional :empty, :message, 7, "proto.utils.Empty"
      optional :keepalive, :message, 8, "proto.Keepalive"
      optional :request_provisioning, :message, 9, "proto.RequestProvisioning"
      optional :should_provision, :message, 10, "proto.ShouldProvision"
      optional :data_frame, :message, 11, "proto.DataFrame"
      optional :report_worker_info, :message, 12, "proto.WorkerInfo"
      optional :worker_should_run, :message, 13, "proto.WorkerShouldRun"
    end
  end
  add_message "proto.Message" do
    optional :encrypted, :bool, 1
    oneof :payload do
      optional :encrypted_message, :bytes, 2
      optional :message, :message, 3, "proto.TunnelMessage"
    end
  end
end

module Proto
  TunnelMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.TunnelMessage").msgclass
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Message").msgclass
end
