# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/error.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.Error" do
    optional :status, :enum, 1, "proto.Error.Status"
    optional :message, :string, 2
    optional :name, :string, 3
  end
  add_enum "proto.Error.Status" do
    value :OK, 0
    value :SOME_ERROR, 1
    value :SERVER_ERROR, 100
    value :NOT_FOUND_ERROR, 200
    value :UNAUTHORIZED, 201
    value :BAD_REQUEST_ERROR, 202
  end
end

module Proto
  Error = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Error").msgclass
  Error::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Error.Status").enummodule
end
