# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/should_provision.proto

require 'google/protobuf'

require 'models/daemon_info_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.ShouldProvision" do
    optional :encrypted_info, :bytes, 1
    optional :temp_public_key, :bytes, 2
  end
  add_message "proto.ShouldProvision.Info" do
    optional :controller_daemon_info, :message, 1, "proto.DaemonInfo"
    optional :daemon_info, :message, 2, "proto.DaemonInfo"
  end
end

module Proto
  ShouldProvision = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ShouldProvision").msgclass
  ShouldProvision::Info = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.ShouldProvision.Info").msgclass
end
