# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/worker_should_run.proto

require 'google/protobuf'

require 'models/utils/account_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.WorkerShouldRun" do
    optional :account, :message, 1, "proto.Account"
    optional :ws_url, :string, 2
  end
end

module Proto
  WorkerShouldRun = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.WorkerShouldRun").msgclass
end
